"""Kitty graphics protocol rendering (tier 1): full-fidelity Nexo image transmission.

Detection lives in `render_context.py` (`RenderContext.kitty_graphics` /
`.use_kitty`) — purely heuristic and environment-based, never an interactive
query/response handshake with the terminal (see that module's docstring for
why: it risks interfering with the session's own stdin read loop or corrupting
terminal state). This module only builds the escape sequence; callers must
check `render_context.use_kitty` first.

The raw PNG bytes (base64-embedded in `_nexo_kitty_payload.py`, generated by
`scripts/embed_nexo_kitty_payload.py` from `assets/nexo-pixel.png`) are
transmitted as-is: Kitty's `f=100` format code means the terminal decodes PNG
natively, so no image library is needed at runtime, matching tier 2's
"no runtime rendering dependency" constraint.
"""

from nexolith.cli._nexo_kitty_payload import NEXO_PIXEL_PNG_BASE64

_CHUNK_SIZE = 4096  # protocol limit per escape-sequence payload chunk
_COLUMNS = 24  # compact header footprint; Kitty scales rows to preserve aspect ratio

_ESCAPE_START = "\x1b_G"
_ESCAPE_END = "\x1b\\"


def render_nexo_kitty_protocol() -> str:
    """Build the Kitty graphics protocol escape sequence(s) that transmit and
    display Nexo at (near-)full fidelity, scaled to `_COLUMNS` terminal columns.

    This is fire-and-forget: the protocol has no synchronous acknowledgement
    read back from the terminal, so a terminal that matches the tier-1 heuristic
    but doesn't actually render this correctly cannot be detected from here —
    only exceptions raised while building or writing this string are catchable.
    Callers must treat any such exception as a tier-1 failure and fall back to
    tier 2's plain ANSI rendering.
    """
    payload = NEXO_PIXEL_PNG_BASE64
    chunks = [payload[index : index + _CHUNK_SIZE] for index in range(0, len(payload), _CHUNK_SIZE)]
    if not chunks:
        chunks = [""]

    parts = []
    for index, chunk in enumerate(chunks):
        is_last = index == len(chunks) - 1
        control = [f"m={0 if is_last else 1}"]
        if index == 0:
            control = ["a=T", "f=100", f"c={_COLUMNS}", *control]
        parts.append(f"{_ESCAPE_START}{','.join(control)};{chunk}{_ESCAPE_END}")
    return "".join(parts)
