"""Dev-time, one-off generator: assets/nexo-pixel.png ->
src/nexolith/cli/_nexo_kitty_payload.py

Stdlib only (base64 of the raw file bytes; no image decoding/re-encoding, so no
Pillow/numpy needed here, unlike scripts/render_nexo_pixel_art.py). Run with:

    uv run python scripts/embed_nexo_kitty_payload.py

Re-run only if the source asset changes.
"""

import base64
import textwrap
from pathlib import Path

SOURCE = Path(__file__).resolve().parent.parent / "assets" / "nexo-pixel.png"
TARGET = (
    Path(__file__).resolve().parent.parent / "src" / "nexolith" / "cli" / "_nexo_kitty_payload.py"
)
LINE_WIDTH = 96


def main() -> None:
    raw = SOURCE.read_bytes()
    encoded = base64.b64encode(raw).decode("ascii")
    wrapped = textwrap.wrap(encoded, width=LINE_WIDTH)

    lines = [
        '"""Generated by scripts/embed_nexo_kitty_payload.py from assets/nexo-pixel.png.',
        "",
        "Do not edit by hand; re-run the script if the source asset changes.",
        '"""',
        "",
        "# Base64 of the raw PNG bytes, transmitted as-is to terminals that support the",
        "# Kitty graphics protocol (f=100: the terminal decodes PNG natively, so no",
        "# image library is needed here, at dev time or at runtime).",
        "NEXO_PIXEL_PNG_BASE64 = (",
    ]
    lines.extend(f'    "{chunk}"' for chunk in wrapped)
    lines.append(")")
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {TARGET} ({len(encoded)} base64 chars, {len(raw)} source bytes)")


if __name__ == "__main__":
    main()
